services:
  backend:
    image: myantony/tcc-backend:1.0.3
    # build: ./TCC-Backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: 1234
      DB_NAME: restapp

  frontend:
    image: myantony/tcc-frontend:1.0.5
    # build: ./TCC-Frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: restapp
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
