services:
  backend:
    image: myantony/tcc-backend:1.0.4  # ✅ Versão correta
    # build: ./TCC-Backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/restapp
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    image: myantony/tcc-frontend:1.0.6
    # build: ./TCC-Frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: restapp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
