apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: tcc-backend
        # Método recomendado: usar versionamento
        image: myantony/tcc-backend:1.0.3
        imagePullPolicy: IfNotPresent

        # Método anterior (com latest):
        # image: docker.io/myantony/tcc-backend:latest
        # imagePullPolicy: IfNotPresent
        # ou apenas remover a linha de imagePullPolicy

        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/restapp
        - name: SPRING_DATASOURCE_USERNAME
          value: user
        - name: SPRING_DATASOURCE_PASSWORD
          value: pass
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: backend
