spring.application.name=restapp

# spring.web.resources.add-mappings=false

# Configurações do datasource - SQLite
# spring.datasource.url=jdbc:sqlite:${user.home}/.restapp/database.db
# spring.datasource.driver-class-name=org.sqlite.JDBC

# Configurações do JPA/Hibernate para SQLite
# spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# SQLite não suporta múltiplas conexões simultâneas com escrita
# spring.datasource.hikari.maximum-pool-size=1

# Configurações antigas (MySQL) - comentadas para referência
# spring.datasource.url=jdbc:mysql://localhost:3306/restapp
# spring.datasource.username=root
# spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

# Origens permitidas no CORS
app.cors.allowed-origins=http://localhost:3000, http://localhost:5173, https://restapp-frontend.onrender.com, https://bshgdnch-5173.brs.devtunnels.ms/, https://bshgdnch-5173.brs.devtunnels.ms/, https://bshgdnch-5173.brs.devtunnels.ms/
# app.cors.allowed-origins=

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.engine.internal.Collections=DEBUG